name: bankpredictionapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  charts_flutter: ^0.12.0
  fl_chart: ^0.68.0
  flutter_bloc: ^8.0.0
  provider: ^6.0.0
  go_router: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/logor.png
    - assets/logt.png
    - assets/cred.png
    - assets/deps.png
    - assets/fraud.png
    - assets/loan.png
    - assets/banking_illustration.png
    # Add any other assets here if needed

flutter_icons:
  android: true
  ios: true
  image_path: "assets/bankenginelogo.png"
  min_sdk_android: 21
