// person.dart

class Person {
  final int age;
  final String job;
  final String marital;
  final String education;
  final int balance;
  final bool personalLoan;
  final bool housingLoan;
  final bool result;

  Person({
    required this.age,
    required this.job,
    required this.marital,
    required this.education,
    required this.balance,
    required this.personalLoan,
    required this.housingLoan,
    required this.result,
  });
}

List<Person> dummyData = [
  Person(
    age: 35,
    job: 'management',
    marital: 'married',
    education: 'tertiary',
    balance: 1100,
    personalLoan: false,
    housingLoan: true,
    result: true,
  ),
  Person(
    age: 22,
    job: 'student',
    marital: 'single',
    education: 'secondary',
    balance: 2000,
    personalLoan: false,
    housingLoan: false,
    result: false,
  ),
  Person(
    age: 45,
    job: 'blue-collar',
    marital: 'divorced',
    education: 'primary',
    balance: 3000,
    personalLoan: true,
    housingLoan: false,
    result: true,
  ),
  Person(
    age: 28,
    job: 'technician',
    marital: 'married',
    education: 'secondary',
    balance: 4000,
    personalLoan: false,
    housingLoan: true,
    result: false,
  ),
  Person(
    age: 50,
    job: 'retired',
    marital: 'divorced',
    education: 'tertiary',
    balance: 5000,
    personalLoan: false,
    housingLoan: false,
    result: true,
  ),
  Person(
    age: 40,
    job: 'admin.',
    marital: 'married',
    education: 'secondary',
    balance: 1000,
    personalLoan: true,
    housingLoan: true,
    result: false,
  ),
  Person(
    age: 55,
    job: 'management',
    marital: 'single',
    education: 'tertiary',
    balance: 5555,
    personalLoan: false,
    housingLoan: true,
    result: true,
  ),
  Person(
    age: 33,
    job: 'technician',
    marital: 'single',
    education: 'secondary',
    balance: 1020,
    personalLoan: false,
    housingLoan: false,
    result: false,
  ),
  Person(
    age: 48,
    job: 'blue-collar',
    marital: 'married',
    education: 'primary',
    balance: 1500,
    personalLoan: true,
    housingLoan: false,
    result: true,
  ),
  Person(
    age: 27,
    job: 'services',
    marital: 'single',
    education: 'secondary',
    balance: 1050,
    personalLoan: false,
    housingLoan: true,
    result: false,
  ),
  Person(
    age: 38,
    job: 'technician',
    marital: 'married',
    education: 'tertiary',
    balance: 1080,
    personalLoan: true,
    housingLoan: true,
    result: true,
  ),
  Person(
    age: 42,
    job: 'entrepreneur',
    marital: 'divorced',
    education: 'primary',
    balance: 1000,
    personalLoan: false,
    housingLoan: false,
    result: false,
  ),
  Person(
    age: 31,
    job: 'admin.',
    marital: 'single',
    education: 'tertiary',
    balance: 1200,
    personalLoan: false,
    housingLoan: true,
    result: true,
  ),
  Person(
    age: 49,
    job: 'technician',
    marital: 'married',
    education: 'secondary',
    balance: 4000,
    personalLoan: true,
    housingLoan: true,
    result: false,
  ),
  Person(
    age: 30,
    job: 'blue-collar',
    marital: 'single',
    education: 'primary',
    balance: 1500,
    personalLoan: false,
    housingLoan: false,
    result: true,
  ),
  Person(
    age: 25,
    job: 'student',
    marital: 'single',
    education: 'secondary',
    balance: 1000,
    personalLoan: false,
    housingLoan: false,
    result: false,
  ),
  Person(
    age: 41,
    job: 'management',
    marital: 'married',
    education: 'tertiary',
    balance: 1000,
    personalLoan: true,
    housingLoan: true,
    result: true,
  ),
  Person(
    age: 36,
    job: 'admin.',
    marital: 'divorced',
    education: 'secondary',
    balance: 1400,
    personalLoan: false,
    housingLoan: false,
    result: false,
  ),
  Person(
    age: 32,
    job: 'technician',
    marital: 'married',
    education: 'primary',
    balance: 1500,
    personalLoan: true,
    housingLoan: true,
    result: true,
  ),
  Person(
    age: 23,
    job: 'services',
    marital: 'single',
    education: 'secondary',
    balance: 1700,
    personalLoan: false,
    housingLoan: true,
    result: false,
  ),
  Person(
    age: 29,
    job: 'blue-collar',
    marital: 'married',
    education: 'primary',
    balance: 1900,
    personalLoan: false,
    housingLoan: false,
    result: true,
  ),
];
