class Person {
  final int income;
  final int age;
  final int experience;
  final int currentJobYears;
  final int currentHouseYears;
  final String maritalStatus; // Married, Single
  final String houseOwnership; // Owned, Rented
  final String carOwnership; // Yes, No
  final String profession; // Engineer, Teacher, Doctor, Chef
  final bool loanStatus;

  Person({
    required this.income,
    required this.age,
    required this.experience,
    required this.currentJobYears,
    required this.currentHouseYears,
    required this.maritalStatus,
    required this.houseOwnership,
    required this.carOwnership,
    required this.profession,
    required this.loanStatus,
  });
  String getLoanStatusString() {
    return loanStatus ? 'Loan Accepted' : 'Loan Denied';
  }
}

List<Person> dummyData = [
  Person(
    income: 50000,
    age: 35,
    experience: 10,
    currentJobYears: 5,
    currentHouseYears: 8,
    maritalStatus: 'Married',
    houseOwnership: 'Owned',
    carOwnership: 'Yes',
    profession: 'Engineer',
    loanStatus: true,
  ),
  Person(
    income: 30000,
    age: 22,
    experience: 1,
    currentJobYears: 0,
    currentHouseYears: 1,
    maritalStatus: 'Single',
    houseOwnership: 'Rented',
    carOwnership: 'No',
    profession: 'Teacher',
    loanStatus: false,
  ),
  Person(
    income: 70000,
    age: 45,
    experience: 20,
    currentJobYears: 15,
    currentHouseYears: 12,
    maritalStatus: 'Divorced',
    houseOwnership: 'Owned',
    carOwnership: 'Yes',
    profession: 'Doctor',
    loanStatus: true,
  ),
  Person(
    income: 40000,
    age: 28,
    experience: 5,
    currentJobYears: 3,
    currentHouseYears: 2,
    maritalStatus: 'Married',
    houseOwnership: 'Rented',
    carOwnership: 'Yes',
    profession: 'Chef',
    loanStatus: true,
  ),
  Person(
    income: 60000,
    age: 50,
    experience: 25,
    currentJobYears: 20,
    currentHouseYears: 18,
    maritalStatus: 'Divorced',
    houseOwnership: 'Owned',
    carOwnership: 'No',
    profession: 'Engineer',
    loanStatus: false,
  ),
  Person(
    income: 45000,
    age: 40,
    experience: 15,
    currentJobYears: 10,
    currentHouseYears: 9,
    maritalStatus: 'Married',
    houseOwnership: 'Owned',
    carOwnership: 'Yes',
    profession: 'Teacher',
    loanStatus: false,
  ),
  Person(
    income: 55000,
    age: 55,
    experience: 30,
    currentJobYears: 25,
    currentHouseYears: 22,
    maritalStatus: 'Single',
    houseOwnership: 'Rented',
    carOwnership: 'Yes',
    profession: 'Doctor',
    loanStatus: false,
  ),
  Person(
    income: 35000,
    age: 33,
    experience: 8,
    currentJobYears: 6,
    currentHouseYears: 4,
    maritalStatus: 'Single',
    houseOwnership: 'Rented',
    carOwnership: 'No',
    profession: 'Chef',
    loanStatus: false,
  ),
  Person(
    income: 65000,
    age: 48,
    experience: 22,
    currentJobYears: 18,
    currentHouseYears: 16,
    maritalStatus: 'Married',
    houseOwnership: 'Owned',
    carOwnership: 'Yes',
    profession: 'Engineer',
    loanStatus: false,
  ),
  Person(
    income: 40000,
    age: 27,
    experience: 4,
    currentJobYears: 2,
    currentHouseYears: 3,
    maritalStatus: 'Single',
    houseOwnership: 'Rented',
    carOwnership: 'Yes',
    profession: 'Teacher',
    loanStatus: false,
  ),
  Person(
    income: 50000,
    age: 38,
    experience: 12,
    currentJobYears: 8,
    currentHouseYears: 6,
    maritalStatus: 'Married',
    houseOwnership: 'Owned',
    carOwnership: 'Yes',
    profession: 'Doctor',
    loanStatus: true,
  ),
  Person(
    income: 35000,
    age: 42,
    experience: 15,
    currentJobYears: 10,
    currentHouseYears: 8,
    maritalStatus: 'Divorced',
    houseOwnership: 'Rented',
    carOwnership: 'No',
    profession: 'Chef',
    loanStatus: false,
  ),
  Person(
    income: 55000,
    age: 31,
    experience: 6,
    currentJobYears: 5,
    currentHouseYears: 4,
    maritalStatus: 'Single',
    houseOwnership: 'Owned',
    carOwnership: 'Yes',
    profession: 'Engineer',
    loanStatus: true,
  ),
  Person(
    income: 37000,
    age: 49,
    experience: 18,
    currentJobYears: 14,
    currentHouseYears: 12,
    maritalStatus: 'Married',
    houseOwnership: 'Rented',
    carOwnership: 'No',
    profession: 'Teacher',
    loanStatus: false,
  ),
  Person(
    income: 48000,
    age: 30,
    experience: 7,
    currentJobYears: 6,
    currentHouseYears: 5,
    maritalStatus: 'Single',
    houseOwnership: 'Owned',
    carOwnership: 'Yes',
    profession: 'Doctor',
    loanStatus: true,
  ),
  Person(
    income: 29000,
    age: 25,
    experience: 2,
    currentJobYears: 1,
    currentHouseYears: 1,
    maritalStatus: 'Single',
    houseOwnership: 'Rented',
    carOwnership: 'No',
    profession: 'Chef',
    loanStatus: false,
  ),
  Person(
    income: 52000,
    age: 41,
    experience: 20,
    currentJobYears: 15,
    currentHouseYears: 12,
    maritalStatus: 'Married',
    houseOwnership: 'Owned',
    carOwnership: 'Yes',
    profession: 'Engineer',
    loanStatus: true,
  ),
  Person(
    income: 42000,
    age: 36,
    experience: 10,
    currentJobYears: 8,
    currentHouseYears: 6,
    maritalStatus: 'Divorced',
    houseOwnership: 'Rented',
    carOwnership: 'No',
    profession: 'Teacher',
    loanStatus: false,
  ),
  Person(
    income: 60000,
    age: 32,
    experience: 12,
    currentJobYears: 10,
    currentHouseYears: 8,
    maritalStatus: 'Married',
    houseOwnership: 'Owned',
    carOwnership: 'Yes',
    profession: 'Doctor',
    loanStatus: true,
  ),
  Person(
    income: 43000,
    age: 23,
    experience: 3,
    currentJobYears: 2,
    currentHouseYears: 1,
    maritalStatus: 'Single',
    houseOwnership: 'Rented',
    carOwnership: 'No',
    profession: 'Chef',
    loanStatus: false,
  ),
  Person(
    income: 56000,
    age: 29,
    experience: 7,
    currentJobYears: 5,
    currentHouseYears: 4,
    maritalStatus: 'Married',
    houseOwnership: 'Owned',
    carOwnership: 'Yes',
    profession: 'Engineer',
    loanStatus: true,
  ),
];
